// solved.ac 태그 슬러그 → 한글 이름. 확신이 없는 희귀 태그는 넣지 않고
// 영어 슬러그만 노출한다 (틀린 번역보다 무표기가 낫다는 판단).
export const TAG_NAMES_KO = {
  math: "수학",
  implementation: "구현",
  dp: "다이나믹 프로그래밍",
  data_structures: "자료 구조",
  graphs: "그래프 이론",
  greedy: "그리디 알고리즘",
  string: "문자열",
  bruteforcing: "브루트포스 알고리즘",
  graph_traversal: "그래프 탐색",
  sorting: "정렬",
  ad_hoc: "애드 혹",
  geometry: "기하학",
  trees: "트리",
  number_theory: "정수론",
  segtree: "세그먼트 트리",
  binary_search: "이분 탐색",
  set: "집합을 사용한 자료 구조",
  constructive: "구성적 알고리즘",
  prefix_sum: "누적 합",
  arithmetic: "사칙연산",
  simulation: "시뮬레이션",
  combinatorics: "조합론",
  bfs: "너비 우선 탐색",
  case_work: "케이스 작업",
  bitmask: "비트마스킹",
  shortest_path: "최단 경로",
  dfs: "깊이 우선 탐색",
  hash_set: "해시를 사용한 집합과 맵",
  dijkstra: "다익스트라",
  sweeping: "스위핑",
  disjoint_set: "분리 집합",
  backtracking: "백트래킹",
  dp_tree: "트리에서의 다이나믹 프로그래밍",
  priority_queue: "우선순위 큐",
  parsing: "파싱",
  tree_set: "트리를 이용한 집합과 맵",
  parametric_search: "매개변수 탐색",
  game_theory: "게임 이론",
  divide_and_conquer: "분할 정복",
  probability: "확률론",
  stack: "스택",
  two_pointer: "투 포인터",
  dp_bitfield: "비트필드를 이용한 다이나믹 프로그래밍",
  lazyprop: "세그먼트 트리를 이용한 지연 전파",
  primality_test: "소수 판정",
  flow: "최대 유량",
  offline_queries: "오프라인 쿼리",
  exponentiation_by_squaring: "분할 정복을 이용한 거듭제곱",
  knapsack: "배낭 문제",
  dag: "방향 비순환 그래프",
  coordinate_compression: "좌표 압축",
  recursion: "재귀",
  arbitrary_precision: "임의 정밀도",
  euclidean: "유클리드 호제법",
  grid_graph: "격자 그래프",
  topological_sorting: "위상 정렬",
  mst: "최소 스패닝 트리",
  precomputation: "전처리",
  linear_algebra: "선형대수학",
  convex_hull: "볼록 껍질",
  sieve: "에라토스테네스의 체",
  bipartite_matching: "이분 매칭",
  inclusion_and_exclusion: "포함과 배제의 원리",
  lca: "최소 공통 조상",
  sparse_table: "스파스 테이블",
  parity: "홀짝성",
  traceback: "역추적",
  hashing: "해싱",
  randomization: "무작위화",
  modular_multiplicative_inverse: "모듈로 곱셈 역원",
  floyd_warshall: "플로이드–워셜",
  scc: "강한 연결 요소",
  smaller_to_larger: "Small to Large",
  line_intersection: "선분 교차 판정",
  sqrt_decomposition: "제곱근 분할법",
  fft: "고속 푸리에 변환",
  calculus: "미적분학",
  trie: "트라이",
  deque: "덱",
  prime_factorization: "소인수분해",
  geometry_3d: "3차원 기하학",
  heuristics: "휴리스틱",
  ternary_search: "삼분 탐색",
  euler_tour_technique: "오일러 경로 테크닉",
  sliding_window: "슬라이딩 윈도우",
  suffix_array: "접미사 배열",
  mcmf: "최소 비용 최대 유량",
  cht: "볼록 껍질을 이용한 최적화",
  sprague_grundy: "스프라그-그런디 정리",
  difference_array: "차이 배열",
  mitm: "중간에서 만나기",
  pythagoras: "피타고라스 정리",
  lis: "최장 증가 부분 수열",
  centroid: "센트로이드",
  permutation_cycle_decomposition: "순열 사이클 분해",
  bitset: "비트셋",
  linearity_of_expectation: "기댓값의 선형성",
  kmp: "KMP",
  gaussian_elimination: "가우스 소거법",
  bipartite_graph: "이분 그래프",
  hld: "트리의 Heavy-Light 분할",
  mfmc: "최대 유량 최소 컷",
  polygon_area: "다각형의 넓이",
  centroid_decomposition: "센트로이드 분할",
  physics: "물리학",
  eulerian_path: "오일러 경로",
  flt: "페르마의 소정리",
  "0_1_bfs": "0-1 BFS",
  flood_fill: "플러드 필",
  articulation: "단절점과 단절선",
  queue: "큐",
  pigeonhole_principle: "비둘기집 원리",
  functional_graph: "함수 그래프",
  "2_sat": "2-SAT",
  tsp: "외판원 순회",
  rerooting: "리루팅",
  dp_digit: "자릿수를 이용한 다이나믹 프로그래밍",
  planar_graph: "평면 그래프",
  point_in_convex_polygon: "볼록 다각형 내부의 점 판정",
  bcc: "이중 연결 요소",
  generating_function: "생성 함수",
  harmonic_number: "조화수",
  euler_phi: "오일러 파이 함수",
  angle_sorting: "각도 정렬",
  linked_list: "연결 리스트",
  crt: "중국인의 나머지 정리",
  invariant: "불변량",
  tree_diameter: "트리의 지름",
  mo: "Mo's 알고리즘",
  maximum_subarray: "최대 부분 배열",
  cactus: "선인장 그래프",
  bellman_ford: "벨만-포드",
  divide_and_conquer_optimization: "분할 정복을 이용한 다이나믹 프로그래밍 최적화",
  extended_euclidean: "확장 유클리드 호제법",
  splay_tree: "스플레이 트리",
  dp_sum_over_subsets: "부분집합의 합 다이나믹 프로그래밍",
  half_plane_intersection: "반평면 교집합",
  pbs: "병렬 이분 탐색",
  rotating_calipers: "회전하는 캘리퍼스",
  regex: "정규 표현식",
  multi_segtree: "다차원 세그먼트 트리",
  pollard_rho: "폴라드 로",
  lcs: "최장 공통 부분 수열",
  slope_trick: "기울기 트릭",
  manacher: "매내처 알고리즘",
  aho_corasick: "아호-코라식",
  miller_rabin: "밀러-라빈 소수 판별법",
  dp_deque: "덱을 이용한 다이나믹 프로그래밍",
  tree_isomorphism: "트리 동형 사상",
  mobius_inversion: "뫼비우스 반전",
  point_in_non_convex_polygon: "비볼록 다각형 내부의 점 판정",
  merge_sort_tree: "머지 소트 트리",
  cartesian_tree: "카르테시안 트리",
  numerical_analysis: "수치해석학",
  link_cut_tree: "링크 컷 트리",
  simulated_annealing: "담금질 기법",
  rabin_karp: "라빈-카프",
  statistics: "통계학",
  li_chao_tree: "Li Chao 트리",
  berlekamp_massey: "벌레캄프-매시",
  hall: "홀의 결혼 정리",
  xor_basis: "XOR 기저",
  z: "Z 알고리즘",
  tree_compression: "트리 압축",
  hungarian: "헝가리안 알고리즘",
  linear_programming: "선형 계획법",
  lucas: "루카스 정리",
  beats: "Segment Tree Beats",
  duality: "쌍대성",
  circulation: "순환 유량",
  voronoi: "보로노이 다이어그램",
  polynomial_interpolation: "다항식 보간법",
  dual_graph: "듀얼 그래프",
  min_enclosing_circle: "최소 외접원",
  monotone_queue_optimization: "단조 큐를 이용한 최적화",
  discrete_log: "이산 로그",
  cdq: "CDQ 분할 정복",
  general_matching: "일반 매칭",
  pick: "픽의 정리",
  suffix_tree: "접미사 트리",
  matroid: "매트로이드",
  tree_decomposition: "트리 분할",
  top_tree: "탑 트리",
  bidirectional_search: "양방향 탐색",
  gradient_descent: "경사 하강법",
  palindrome_tree: "회문 트리",
  dancing_links: "댄싱 링크",
  bayes: "베이즈 정리",
  delaunay: "들로네 삼각분할",
  stable_marriage: "안정 결혼 문제",
  knuth: "Knuth's Optimization",
};

export function tagLabel(tag) {
  const ko = TAG_NAMES_KO[tag];
  return ko ? `${tag} (${ko})` : tag;
}
